//! Resource health checking utilities.
//!
//! Provides [`PoolHealthReport`] — a snapshot of a connection pool's health
//! state including resource counts and the time spent collecting the report.

use std::time::Duration;

use serde::{Deserialize, Serialize};

/// Snapshot of a connection pool's health state.
///
/// Generated by [`ConnectionPool::health_report`](crate::pool::ConnectionPool::health_report).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolHealthReport {
    /// Total managed resources (idle + active).
    pub total_resources: usize,
    /// Resources currently checked out.
    pub active_resources: usize,
    /// Resources sitting idle in the pool.
    pub idle_resources: usize,
    /// Wall-clock time taken to produce this report.
    pub health_check_time: Duration,
}

impl PoolHealthReport {
    /// Returns the utilization ratio (active / total), or 0.0 if the pool is empty.
    pub fn utilization(&self) -> f64 {
        if self.total_resources == 0 {
            0.0
        } else {
            self.active_resources as f64 / self.total_resources as f64
        }
    }

    /// Returns `true` if the pool has no resources at all.
    pub fn is_empty(&self) -> bool {
        self.total_resources == 0
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn utilization_with_resources() {
        let report = PoolHealthReport {
            total_resources: 10,
            active_resources: 7,
            idle_resources: 3,
            health_check_time: Duration::from_millis(1),
        };
        let util = report.utilization();
        assert!((util - 0.7).abs() < f64::EPSILON);
    }

    #[test]
    fn utilization_empty_pool() {
        let report = PoolHealthReport {
            total_resources: 0,
            active_resources: 0,
            idle_resources: 0,
            health_check_time: Duration::from_millis(0),
        };
        assert_eq!(report.utilization(), 0.0);
    }

    #[test]
    fn is_empty() {
        let empty = PoolHealthReport {
            total_resources: 0,
            active_resources: 0,
            idle_resources: 0,
            health_check_time: Duration::from_millis(0),
        };
        assert!(empty.is_empty());

        let non_empty = PoolHealthReport {
            total_resources: 1,
            active_resources: 1,
            idle_resources: 0,
            health_check_time: Duration::from_millis(0),
        };
        assert!(!non_empty.is_empty());
    }

    #[test]
    fn clone_and_debug() {
        let report = PoolHealthReport {
            total_resources: 5,
            active_resources: 2,
            idle_resources: 3,
            health_check_time: Duration::from_millis(10),
        };
        let cloned = report.clone();
        assert_eq!(cloned.total_resources, 5);
        let debug_str = format!("{:?}", report);
        assert!(debug_str.contains("PoolHealthReport"));
    }
}
